### ISSUE TITLE
Auto scroll not working

### ISSUE THREAD

**Issue by ppamorim** [Swordfish90/cool-retro-term#301]
Hello.
The auto scroll of this terminal is not working, I installed the last version and build the source. I'm using the OSX 10.11.5.

**Comment by Skater101b** [comment]
I have the same problem. When I cat out info, I can not scroll up in the terminal. I can scroll up through commands, but having the ability to scroll up in the terminal is kind of a deal breaker for me. Which would be a bummer since this is a super cool terminal.  I believe we are talking about the same thing.

**Comment by Skater101b** [comment]
I started it today and the scrolling works like it should, perhaps it was related to a preference I had set, but now ctrl+C doesn't work to interrupt a command.

**Comment by otherjoel** [comment]
If I do `ls -l` in a folder with lots of files, the terminal does not auto-scroll to the bottom of the listing; instead the listing continues right past the bottom of the screen. The command prompt is also off-screen at this point. You can't use your mouse to scroll down to see it either; in fact the only way to see your command prompt again is to type `clear` and hit Enter.

Further testing: if I do this in fullscreen mode on a 13″ Retina MacBook Pro:

    clear; for i in {1..50}; do echo $i; done;

Then I see numbers 1–40 on the screen and the command prompt is invisible. I have to hit Enter 28 times before the display will scroll at all (it starts scrolling on the 29th keystroke), which to me says that the terminal thinks it has 68 rows to work with instead of only 40.

I believe this is the same auto-scrolling problem @ppamorim is describing. (@Skater101b seems to be talking about manually scrolling up in the terminal history, which is a different thing.)

**Comment by Integralist** [comment]
Yeah so similar issue for me, whether it be `ls -la` or opening Vim and not being able to see the Ex bar at the bottom of the screen

**Comment by mattstvartak** [comment]
Also having this problem. Typed "testing" and hit enter and it didn't appear for another 35 lines.

**Comment by davehouse** [comment]
I see this problem also on a macbookpro with retina screen. It looks like the column by row counts are scaled 2x of what is actually visible. Maybe the retina pixel density is affecting a size measurement but being applied twice.

**Comment by izznogooood** [comment]
Same problem, osx.

**Comment by angelo** [comment]
Same issue here, OSX 10.10.5, 27" iMac. I've tried various screen scalings, doesn't have any impact on the issue.

**Comment by davehouse** [comment]
The problem is fixed by turning off retina scaling (Set display to "Scaled" > "More Space" to scale the ui to actual/1x pixels in OSX). So it looks like a problem with the retina/hidpi scaling in the code.

**Comment by singlerider** [comment]
The problem still persists for me on 15 inch Macbook Pro, even after adjusting scaling.

**Comment by davehouse** [comment]
This fixed the scaling problem for me to keep the terminal content in the crt display area (cols, lines being actual crt display area), https://bugreports.qt.io/browse/QTBUG-48972.

Setting the environment variable QT_SCALE_FACTOR=0.5 to un-scale from my 2x/retina setting in OSX:
```
$ QT_SCALE_FACTOR=0.5 cool-retro-term.app/Contents/MacOS/cool-retro-term
```
![image](https://cloud.githubusercontent.com/assets/5540936/22387178/a2da5474-e497-11e6-806d-9fb903053263.png)
![image](https://cloud.githubusercontent.com/assets/5540936/22387226/cf23b778-e497-11e6-992c-e11a4e187321.png)

**Comment by hery84** [comment]
QT_SCALE_FACTOR=0.5 open cool-retro-term.app
