### ISSUE TITLE
Can't install on Ubuntu 16.04 or 16.10

### ISSUE THREAD

**Issue by Schwarzer-Schwan** [Swordfish90/cool-retro-term#323]
I can't install it on Ubuntu 16.04 or 16.10. Also, some of the dependencies aren't available anymore. Downloaded qt5-default to compile from source but get the following error:

`Project ERROR: Unknown module(s) in QT: qml quick
Makefile:43: recipe for target 'sub-qmltermwidget-make_first-ordered' failed
make: *** [sub-qmltermwidget-make_first-ordered] Error 3`

I love this terminal please fix it soon!

**Comment by tomchiverton** [comment]
Installs fine for me on 16.04.1 LTS 64 bit, from the 3rd party PPA; no need to build it yourself.

**Comment by tomchiverton** [comment]
So it's only 16.10 that isn't supported by the PPA then ?

**Comment by mardukbp** [comment]
It compiles on Ubuntu 16.04 with Qt from the Qt website.

**Comment by B-greg** [comment]
When i try to install on ubuntu 16.06 i got these errors:
dpkg: dependency problems prevent configuration of cool-retro-term:
 cool-retro-term depends on qtdeclarative5-controls-plugin; however:
  Package qtdeclarative5-controls-plugin is not installed.
 cool-retro-term depends on qtdeclarative5-dialogs-plugin; however:
  Package qtdeclarative5-dialogs-plugin is not installed.

The problem is Package qtdeclarative5-controls-plugin  is deprecated
However the following packages replace it:
  qml-module-qtquick-controls:i386 qml-module-qtquick-controls

But these packages are not reconised by cool-old-term

**Comment by tomchiverton** [comment]
@B-greg did you mean 16.04 ?
If so, there is now a 1.0.1 release that should fix the issue.

**Comment by B-greg** [comment]
@tomchiverton  My bad, i mean ubuntu 16.10. 
I try with new package but the error is still here.
But its work fine when I install it by source code.

**Comment by DiegoCalzolari** [comment]
I've succesfully installed on 16.04 using the given repository but it just show up for a moment then goes down with the following message:

default KB_LAYOUT_DIR:  "/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts" 
QObject::connect: No such slot Konsole::TerminalDisplay_QML_150::close()
loadAllColorSchemes 
Both point size and pixel size set. Using pixel size.
Session::run() - program: "/bin/bash" 
Session::run() - arguments: ("") 
started! 

Is it just me? Any suggestion?

**Comment by tomchiverton** [comment]
On 16.04.2 LTS 64bit, if I start cool-retro-term from a Konsole window, I see the output

```
default KB_LAYOUT_DIR:  "/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts" 
QObject::connect: No such slot Konsole::TerminalDisplay_QML_42::close()
loadAllColorSchemes 
Both point size and pixel size set. Using pixel size.
Session::run() - program: "/bin/bash" 
Session::run() - arguments: ("") 
started! 
```
but crt window appears and works fine, so the messages are fine.

Try `strace cool-retro-term` ?

**Comment by DiegoCalzolari** [comment]
Sorry for bothering, it turned out to be a script that changes the background color of every terminal I opened. I've disabled it and now everything is okay.
